### PR TITLE
Fix documented type in test_unhandled_state

### PR DESCRIPTION
**Pull request by imjoehaines**
The documented type for this is currently a Hash but it's actually an Integer
https://bugsnag.github.io/maze-runner/top-level-namespace.html#test_unhandled_state-instance_method

### CODE REVIEW

**Review by twometresteve — APPROVED** [review]
There are lots of Rubocop violations in the file that could be resolved while we're there (if you have a friendly IDE), but happy to accept this as is!

**Comment by imjoehaines** [comment]
> There are lots of Rubocop violations in the file that could be resolved while we're there (if you have a friendly IDE), but happy to accept this as is!

I fixed all the errors on the latest version (1.4.2); it'd be good to add Rubocop to the gemfile so everyone runs the same version

**Review by twometresteve — APPROVED** [review]
LGTM

**Comment by twometresteve** [comment]
> > There are lots of Rubocop violations in the file that could be resolved while we're there (if you have a friendly IDE), but happy to accept this as is!
> 
> I fixed all the errors on the latest version (1.4.2); it'd be good to add Rubocop to the gemfile so everyone runs the same version

Nice!  And yes, agreed - to date I've just ben ironing out violations as I go, there were so many.  But it would be good to tighten the screw at some point and even build compliance into CI (without just having a whole load of TODOs).

**Pull request merged**
