### PR TITLE
Add step to check null request part

### PR DESCRIPTION
**Pull request by fractalwrench**
Adds a step to check that a request part is null.

### CODE REVIEW

**Comment by Cawllec** [comment]
Is there a way we can make it clearer this is for multipart requests?

**Comment by fractalwrench** [comment]
What syntax would work better? Perhaps something like `The part "(.+)" for multipart request is null`?

We'd also need to update other steps and any existing scenarios.

**Comment by fractalwrench** [comment]
@kattrali @bengourley do you have thoughts on the above?

**Comment by fractalwrench** [comment]
Updated the syntax as discussed.

**Pull request merged**
